version: 1.0.0-{build}

assembly_info:
  patch: true
  file: src\headlessIE.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# Install scripts. (runs after repo cloning)
install:
  # Update npm itself
  - npm install -g npm

before_test:
  # Prepare test environment.
  - mkdir node_modules 2> NUL:
  - npm install tape express tap-spec
  - set PATH=%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%

# Post-install test scripts.
test_script:
  # run tests
  - node test/base.js | tap-spec

after_build:
  - 7z a headlessIE-%APPVEYOR_BUILD_VERSION%.zip .\bin\headlessIE.exe

# Caching npm parts
cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules

artifacts:
  - path: headlessIE-$(APPVEYOR_BUILD_VERSION).zip
    name: HeadlessIE
    type: zip

deploy:
  - provider: FTP
    host: dl.free.fr
    username:
      secure: ukFGKeaeBTM48K8mUocLCwyzIcyso5l/Dny7N88eEoc=
    password:
      secure: ukFGKeaeBTM48K8mUocLCwyzIcyso5l/Dny7N88eEoc=
