version: 1.0.0-{build}

assembly_info:
  patch: true
  file: src\headlessIE.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

# Install scripts. (runs after repo cloning)
install:
  # Update npm itself.
  - npm install -g npm

before_test:
  # Prepare test environment.
  - mkdir node_modules 2> NUL:
  - npm install tape express tap-spec
  - set PATH=%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%

# Post-install test scripts.
test_script:
  # Run tests.
  - node test/base.js | tap-spec

# Caching npm parts.
cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> appveyor.yml  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> appveyor.yml         # npm cache
  - node_modules -> appveyor.yml                                        # local npm modules
